/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CriaTreino.java
 *
 * Created on 23/11/2010, 14:18:06
 */

package gui;

import projeto.Aparelho;
import projeto.Exercicio;
import projeto.GrupoMuscular;
import java.util.*;
/**
 *
 * @author Diego Pereira
 */
public class CriaTreino extends javax.swing.JPanel {
    private GrupoMuscular grupo ;
    private Exercicio exercicio;
    private Aparelho aparelho;
    /** Creates new form CriaTreino */
    public CriaTreino() {
        initComponents();
        jLabel1.setText("Editando o Treino de "+ControladorPrincipal.usuarioSendoEditado.getNome());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listGrupos = new java.awt.List();
        listExercicios = new java.awt.List();
        listAparelhos = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVerGrupo = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        listGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listGruposMouseClicked(evt);
            }
        });

        listExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listExerciciosMouseClicked(evt);
            }
        });
        listExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listExerciciosActionPerformed(evt);
            }
        });

        listAparelhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAparelhosActionPerformed(evt);
            }
        });

        jLabel3.setText("Exercicios");

        jLabel4.setText("Aparelhos");

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVerGrupo.setText("Ver Grupos");
        jButtonVerGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(listGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(listExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(listAparelhos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButtonVerGrupo)
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButtonVoltar)
                .addGap(104, 104, 104)
                .addComponent(jButtonSalvar)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButtonVerGrupo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listExercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(listGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(listAparelhos, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonSalvar))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listAparelhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAparelhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listAparelhosActionPerformed

    private void listExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listExerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listExerciciosActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
     ControladorPrincipal.janela.setContentPane(ControladorPrincipal.procuraAluno);
     ControladorPrincipal.janela.setVisible(true);
     listAparelhos.removeAll();
     listExercicios.removeAll();
     listGrupos.removeAll();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVerGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerGrupoActionPerformed
        for(int c = 0 ; c < ControladorPrincipal.gruposMusculares.size();c++){
            listGrupos.add(ControladorPrincipal.gruposMusculares.get(c).getGrupoMuscular());
        }

    }//GEN-LAST:event_jButtonVerGrupoActionPerformed

    private void listGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listGruposMouseClicked

        for (int c = 0 ; c < ControladorPrincipal.gruposMusculares.size();c++){
            if ( ControladorPrincipal.gruposMusculares.get(c).getGrupoMuscular().equals(listGrupos.getSelectedItem())){
                grupo = ControladorPrincipal.gruposMusculares.get(c);
            }
        }
        for ( int d = 0 ; d < ControladorPrincipal.listaDeExercicio.size();d++){
               if ( ControladorPrincipal.listaDeExercicio.get(d).getGrupoMuscular().getGrupoMuscular().equals(grupo.getGrupoMuscular())){
                   listExercicios.add( ControladorPrincipal.listaDeExercicio.get(d).getNome());
               }
        }
    }//GEN-LAST:event_listGruposMouseClicked

    private void listExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listExerciciosMouseClicked
        for (int f = 0 ; f < ControladorPrincipal.listaDeExercicio.size();f++){
            if ( ControladorPrincipal.listaDeExercicio.get(f).getNome().equals(listExercicios.getSelectedItem())){
                exercicio = ControladorPrincipal.listaDeExercicio.get(f);

            }

        }
        for ( int g = 0 ; g < exercicio.getListaDeAparelho().size();g++){
            listAparelhos.add(exercicio.getListaDeAparelho().get(g).getNome());
        }
    }//GEN-LAST:event_listExerciciosMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        ControladorPrincipal.usuarioSendoEditado.getTreino().addGrupoMusucular(grupo);
        ControladorPrincipal.usuarioSendoEditado.getTreino().addExercicio(exercicio);
        listAparelhos.removeAll();
        listExercicios.removeAll();
        listGrupos.removeAll();
        System.out.print(ControladorPrincipal.usuarioSendoEditado.getTreino().toString());
      
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerGrupo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.List listAparelhos;
    private java.awt.List listExercicios;
    private java.awt.List listGrupos;
    // End of variables declaration//GEN-END:variables

}
