/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAdmin.java
 *
 * Created on 17/11/2010, 20:34:25
 */

package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Abimael
 */
public class MenuAdmin extends javax.swing.JPanel {

    /** Creates new form MenuAdmin */
    public MenuAdmin() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonProcurarAluno = new javax.swing.JButton();
        jButtonCadastraExercicio = new javax.swing.JButton();
        jButtonEditaExercicio = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonRemoveAparelho = new javax.swing.JButton();
        jButtonTreinosPendentes = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setText("CADASTRAR ALUNO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonProcurarAluno.setText("PROCURAR ALUNO");
        jButtonProcurarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarAlunoActionPerformed(evt);
            }
        });

        jButtonCadastraExercicio.setText("CADASTRAR EXERCICIO");
        jButtonCadastraExercicio.setMaximumSize(new java.awt.Dimension(125, 23));
        jButtonCadastraExercicio.setMinimumSize(new java.awt.Dimension(125, 23));
        jButtonCadastraExercicio.setPreferredSize(new java.awt.Dimension(125, 23));
        jButtonCadastraExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraExercicioActionPerformed(evt);
            }
        });

        jButtonEditaExercicio.setText("EDITAR EXERCICIO");
        jButtonEditaExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaExercicioActionPerformed(evt);
            }
        });

        jButton5.setText("CADASTRAR APARELHO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("CARREGAR APARELHOS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButtonRemoveAparelho.setText("REMOVER APARELHO");
        jButtonRemoveAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAparelhoActionPerformed(evt);
            }
        });

        jButtonTreinosPendentes.setText("LISTAR ALUNOS COM TREINOS PENDENTES");
        jButtonTreinosPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreinosPendentesActionPerformed(evt);
            }
        });

        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Alunos");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Exercicios");

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Treinos");

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Aparelhos");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Bem Vindo David");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTreinosPendentes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonProcurarAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButtonCadastraExercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEditaExercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRemoveAparelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(125, 125, 125))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButtonSair)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel5)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveAparelho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonProcurarAluno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastraExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditaExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)))
                .addComponent(jButtonTreinosPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        //ControladorPrincipal.janela.setVisible(false);
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.loginGeral);
        ControladorPrincipal.janela.setVisible(true);
       

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ControladorPrincipal.janela.setVisible(false);
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.cadastraAluno);
        ControladorPrincipal.janela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonProcurarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarAlunoActionPerformed
     // ControladorPrincipal.janela.setVisible(false);
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.procuraAluno);
        ControladorPrincipal.janela.setVisible(true);
    }//GEN-LAST:event_jButtonProcurarAlunoActionPerformed

    private void jButtonCadastraExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraExercicioActionPerformed
        if(ControladorPrincipal.aparelhos.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nao é possivel cadastrar exercicios\nagora,pois nao ha nenhum aparelho\ncadastrado");
            return;
        }
        



        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.cadastraExercicio);
        ControladorPrincipal.janela.setVisible(true);



    }//GEN-LAST:event_jButtonCadastraExercicioActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         ControladorPrincipal.janela.setContentPane(ControladorPrincipal.cadastraAparelho);
        ControladorPrincipal.janela.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonEditaExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaExercicioActionPerformed
         // verificar se a lista de aparelhos esta vazia
                        if(ControladorPrincipal.aparelhos == null|| ControladorPrincipal.aparelhos.isEmpty()){
                            JOptionPane.showMessageDialog(null,"\nNao ha nenhum aparelho cadastrado!");

                                return;
                        }

                        // verifica se ha exercicio cadastrado
                        if(ControladorPrincipal.listaDeExercicio == null||ControladorPrincipal.listaDeExercicio.isEmpty()){
                            JOptionPane.showMessageDialog(null,"Nenhum exercicio cadastrado!");
                      
                                return;
                        }
                       ControladorPrincipal.janela.setContentPane(ControladorPrincipal.escolheExercicio);
                       ControladorPrincipal.janela.setVisible(true);

    }//GEN-LAST:event_jButtonEditaExercicioActionPerformed

    private void jButtonTreinosPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreinosPendentesActionPerformed
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.treinoPendentes);
        ControladorPrincipal.janela.setVisible(true);

    }//GEN-LAST:event_jButtonTreinosPendentesActionPerformed

    private void jButtonRemoveAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAparelhoActionPerformed
       ControladorPrincipal.janela.setContentPane(ControladorPrincipal.remocaoDeAparelhos);
       ControladorPrincipal.janela.setVisible(true);

    }//GEN-LAST:event_jButtonRemoveAparelhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCadastraExercicio;
    private javax.swing.JButton jButtonEditaExercicio;
    private javax.swing.JButton jButtonProcurarAluno;
    private javax.swing.JButton jButtonRemoveAparelho;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTreinosPendentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
