/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemocaoAparelhos.java
 *
 * Created on 26/11/2010, 01:32:17
 */

package gui;

import javax.swing.JOptionPane;
import projeto.Aparelho;
import projeto.Exercicio;

/**
 *
 * @author Abimael
 */
public class RemocaoAparelhos extends javax.swing.JPanel {

    /** Creates new form RemocaoAparelhos */
    public RemocaoAparelhos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jButtonListarAparelhos = new javax.swing.JButton();
        jSpinnerQtdAparelhos = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();

        jLabel1.setText("Remover Aparelhos");

        jButtonListarAparelhos.setText("Listar Aparelhos");
        jButtonListarAparelhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarAparelhosActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade a ser removida");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jSpinnerQtdAparelhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButtonVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemover))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtonListarAparelhos)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jButtonListarAparelhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSpinnerQtdAparelhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVoltar)
                            .addComponent(jButtonRemover))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.menuAdmin);
       ControladorPrincipal.janela.setVisible(true);
       list1.removeAll();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonListarAparelhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarAparelhosActionPerformed
        if(list1.getItemCount()==0){
        for ( int c = 0 ; c < ControladorPrincipal.aparelhos.size();c++){
            list1.add(ControladorPrincipal.aparelhos.get(c).getNome());
        }}
    }//GEN-LAST:event_jButtonListarAparelhosActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        
            String nomeDoAparelho = list1.getSelectedItem();

          
            for(Exercicio exercicio: ControladorPrincipal.listaDeExercicio){
            	for(Aparelho aparelho: exercicio.getListaDeAparelho()){
            		if(aparelho.getNome().equals(nomeDoAparelho)){

            	
            			Integer quantidadeDeAparelho = (Integer) jSpinnerQtdAparelhos.getValue();
                                 if (quantidadeDeAparelho <= 0){
                                       JOptionPane.showMessageDialog(null,"Quantidade invalida!");
                                       return;
                                 }
            			try{
            		

            				if(aparelho.setQuantidadeDeAparelho(aparelho.getQuantidadeDeAparelho() - quantidadeDeAparelho)){
            				JOptionPane.showMessageDialog(null,"Remocao de aparelhos realizada com sucesso!");
                                   
            			              System.out.println(aparelho.getQuantidadeDeAparelho());
            				}else{
            				     	JOptionPane.showMessageDialog(null,"Nao foi possivel remover os aparelhos, devido a quantidade que voce digitou!");
                                       
      
            				}

            			}catch (Exception excecao){
            			   JOptionPane.showMessageDialog(null,"Caracteres invalidos!");
                                

            			}
            		}
            	}
            }
    }//GEN-LAST:event_jButtonRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarAparelhos;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinnerQtdAparelhos;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

}
