/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrimeiroLogin.java
 *
 * Created on 17/11/2010, 20:12:57
 */

package gui;

/**
 *
 * @author Abimael
 */
public class PrimeiroLogin extends javax.swing.JPanel {

    /** Creates new form PrimeiroLogin */
    public PrimeiroLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaudacao = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldLoginAdmin = new javax.swing.JTextField();
        jTextFieldNovaSenhaAdmin = new javax.swing.JTextField();
        jButtonLogarAdmin = new javax.swing.JButton();

        jLabelSaudacao.setText("BEM VINDO!");

        jLabelLogin.setText("LOGIN :");

        jLabelSenha.setText("SENHA :");

        jTextFieldLoginAdmin.setEditable(false);
        jTextFieldLoginAdmin.setText("admin");

        jTextFieldNovaSenhaAdmin.setText("Nova Senha");

        jButtonLogarAdmin.setText("LOGAR");
        jButtonLogarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelSaudacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNovaSenhaAdmin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonLogarAdmin)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaudacao)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jTextFieldNovaSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonLogarAdmin)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarAdminActionPerformed
        try{
        ControladorPrincipal.admin.setSenha(jTextFieldNovaSenhaAdmin.getText());
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
        jTextFieldNovaSenhaAdmin.setText("");
        System.out.print(ControladorPrincipal.admin.getSenha());
        ControladorPrincipal.janela.setVisible(false);
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.menuAdmin);
        ControladorPrincipal.janela.setVisible(true);
    }//GEN-LAST:event_jButtonLogarAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogarAdmin;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSaudacao;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JTextField jTextFieldLoginAdmin;
    private javax.swing.JTextField jTextFieldNovaSenhaAdmin;
    // End of variables declaration//GEN-END:variables

}
